export default [
  { id: '1', value: 'W' },
  { id: '1.025', value: 'e' },
  { id: '1.05', value: '.', className: 'space' },
  { id: '1.075', value: 'b' },
  { id: '1.2', value: 'u' },
  { id: '1.225', value: 'i' },
  { id: '1.25', value: 'l' },
  { id: '1.275', value: 'd' },
  { id: '1.3', value: '.', className: 'space' },
  { id: '1.325', value: 'u' },
  { id: '1.35', value: 'n' },
  { id: '1.375', value: 'f' },
  { id: '1.4', value: 'o' },
  { id: '1.425', value: 'r' },
  { id: '1.45', value: 'g' },
  { id: '1.475', value: 'e' },
  { id: '1.5', value: 't' },
  { id: '1.525', value: 't' },
  { id: '1.55', value: 'a' },
  { id: '1.575', value: 'b' },
  { id: '1.6', value: 'l' },
  { id: '1.625', value: 'e' },
  { id: '1.65', value: '.', className: 'space' },
  { id: '1.675', value: 'w' },
  { id: '1.7', value: 'e' },
  { id: '1.725', value: 'b' },
  { id: '1.75', value: 's' },
  { id: '1.775', value: 'i' },
  { id: '1.8', value: 't' },
  { id: '1.825', value: 'e' },
  { id: '1.85', value: 's' },
  { id: '1.875', value: '.', className: 'space' },
  { id: '1.9', value: 'f' },
  { id: '1.925', value: 'o' },
  { id: '1.95', value: 'r' },
  { id: '1.975', value: '.', className: 'space' },
  { id: '2', value: 'b' },
  { id: '2.025', value: 'r' },
  { id: '2.05', value: 'a' },
  { id: '2.075', value: 'n' },
  { id: '2.1', value: 'd' },
  { id: '2.125', value: 's' },
  { id: '2.15', value: '.', className: 'space' },
  { id: '2.175', value: 'a' },
  { id: '2.2', value: 'n' },
  { id: '2.225', value: 'd' },
  { id: '2.25', value: '.', className: 'space' },
  { id: '2.275', value: 'c' },
  { id: '2.3', value: 'r' },
  { id: '2.325', value: 'e' },
  { id: '2.35', value: 'a' },
  { id: '2.375', value: 't' },
  { id: '2.4', value: 'i' },
  { id: '2.425', value: 'v' },
  { id: '2.45', value: 'e' },
  { id: '2.475', value: 's' },
]